version: '3.8'

name: notes_prod

secrets:
  notes-app-notes-db-postgres-passwd:
    external: true
  notes-app-access-token-jwt-secret:
    external: true
  notes-app-microservice-token-jwt-secret:
    external: true
  notes-app-google-client-id:
    external: true
  notes-app-google-csrf-token-jwt-secret:
    external: true
  notes-app-facebook-app-id:
    external: true
  notes-app-facebook-app-secret:
    external: true
  notes-app-facebook-csrf-token-jwt-secret:
    external: true
  notes-app-frontend-server-public-key:
    external: true
  notes-app-cookie-secret:
    external: true
  notes-app-frontend-server-auth-private-key:
    external: true
  notes-app-frontend-server-auth-passphrase:
    external: true
  notes-app-pgadmin-default-password:
    external: true

volumes:
  notes-frontend-public:
  notes-frontend-views:
  notes-db-data:

networks:
  notes-nginx-reversive-proxy:
  notes-backend:
  notes-notes-db:

services:
  nginx-reversive-proxy:
    build:
      dockerfile: Dockerfile
      context: ./nginx/
    volumes:
      - ./nginx/log/:/var/log/nginx/:rw
    stop_signal: SIGTERM
    stop_grace_period: 20s
    init: true
    restart: always
    depends_on:
      backend:
        condition: service_healthy
      frontend-server:
        condition: service_healthy
      pgadmin4:
        condition: service_started
    ports:
      - target: 80
        host_ip: 0.0.0.0
        published: 80
        protocol: tcp
        mode: host
      - '127.0.0.1:5050:5050'
      - '127.0.0.1:9929:9929'
      - '127.0.0.1:9928:9928'
    networks:
      - notes-nginx-reversive-proxy

  backend:
    build:
      dockerfile: Dockerfile
      target: prod
      context: ./backend/
    stop_signal: SIGTERM
    stop_grace_period: 20s
    init: true
    restart: always
    secrets:
      - notes-app-access-token-jwt-secret
      - notes-app-microservice-token-jwt-secret
      - notes-app-google-client-id
      - notes-app-google-csrf-token-jwt-secret
      - notes-app-facebook-app-id
      - notes-app-facebook-app-secret
      - notes-app-facebook-csrf-token-jwt-secret
      - notes-app-frontend-server-public-key
      - notes-app-cookie-secret
    environment:
      NODE_ENV: production
      PORT: 3000
      ACCESS_TOKEN_JWT_SECRET: /run/secrets/notes-app-access-token-jwt-secret
      MICROSERVICE_TOKEN_JWT_SECRET: /run/secrets/notes-app-microservice-token-jwt-secret
      GOOGLE_CLIENT_ID: /run/secrets/notes-app-google-client-id
      GOOGLE_CSRF_TOKEN_JWT_SECRET: /run/secrets/notes-app-google-csrf-token-jwt-secret
      FACEBOOK_APP_ID: /run/secrets/notes-app-facebook-app-id
      FACEBOOK_APP_SECRET: /run/secrets/notes-app-facebook-app-secret
      FACEBOOK_APP_DEVELOPMENT_ACCESS_TOKEN: 'null'
      FACEBOOK_CSRF_TOKEN_JWT_SECRET: /run/secrets/notes-app-facebook-csrf-token-jwt-secret
      FRONTEND_SERVER_PUBLIC_KEY: /run/secrets/notes-app-frontend-server-public-key
      COOKIE_SECRET: /run/secrets/notes-app-cookie-secret
      PGPASSWORD: /run/secrets/notes-app-notes-db-postgres-passwd
      PGUSER: postgres
      PGDATABASE: notes
      PGPORT: 5432
      PGHOST: notes-db
    networks:
      notes-nginx-reversive-proxy:
        priority: 10
      notes-backend:
        priority: 20
      notes-notes-db:
        priority: 30
    depends_on:
      notes-db:
        condition: service_healthy
    volumes:
      - ./backend/log/:/var/log/backend/:rw

  frontend-server:
    build:
      dockerfile: Dockerfile
      target: prod
      context: ./frontend-server/
    stop_signal: SIGTERM
    stop_grace_period: 20s
    init: true
    restart: always
    secrets:
      - notes-app-frontend-server-auth-private-key
      - notes-app-frontend-server-auth-passphrase
    environment:
      NODE_ENV: production
      PORT: 3000
      AUTH_PRIVATE_KEY: /run/secrets/notes-app-frontend-server-auth-private-key
      AUTH_PASSPHRASE: /run/secrets/notes-app-frontend-server-auth-passphrase
      BACKEND_URL: http://swarm-backend:3000
      BACKEND_TOKEN: initial
    networks:
      notes-nginx-reversive-proxy:
        priority: 10
      notes-backend:
        priority: 20
    volumes:
      - notes-frontend-public:/usr/app/frontend/public/:ro
      - notes-frontend-views:/usr/app/frontend/views/:ro
      - ./frontend-server/log/:/var/log/frontend-server/:rw
    depends_on:
      frontend-static:
        condition: service_started
      backend:
        condition: service_healthy

  frontend-static:
    build:
      dockerfile: Dockerfile
      target: prod
      context: ./frontend/
    stop_signal: SIGTERM
    stop_grace_period: 20s
    init: true
    restart: always
    volumes:
      - notes-frontend-public:/usr/app/frontend/public/:rw
      - notes-frontend-views:/usr/app/frontend/views/:rw

  notes-db:
    build:
      dockerfile: Dockerfile
      target: prod
      context: ./notes-db/
      shm_size: 256mb
    secrets:
      - notes-app-notes-db-postgres-passwd
    environment:
      POSTGRES_PASSWORD: /run/secrets/notes-app-notes-db-postgres-passwd
      POSTGRES_DB: notes
      POSTGRES_USER: postgres
      POSTGRES_PORT: 5432
      POSTGRES_HOST: 0.0.0.0
    stop_signal: SIGTERM
    stop_grace_period: 20s
    init: true
    restart: always
    volumes:
      - ./notes-db/log/:/var/log/postgres/:rw
      - notes-db-data:/var/lib/postgresql/data/:rw
    shm_size: 256mb
    networks:
      - notes-notes-db

  task-manager:
    build:
      dockerfile: Dockerfile
      target: prod
      context: ./task-manager/
    secrets:
      - notes-app-notes-db-postgres-passwd
    environment:
      PRODUCTION: true
      BACKUP_KEEP_DAYS: 1
      NOTES_POSTGRES_PASSWORD: /run/secrets/notes-app-notes-db-postgres-passwd
      NOTES_POSTGRES_DATABASE: notes
      NOTES_POSTGRES_USER: postgres
      NOTES_POSTGRES_HOST: notes-db
      NOTES_POSTGRES_PORT: 5432
    stop_signal: SIGTERM
    stop_grace_period: 20s
    init: true
    restart: always
    depends_on:
      notes-db:
        condition: service_healthy
      backend:
        condition: service_healthy
    networks:
      notes-backend:
        priority: 10
      notes-notes-db:
        priority: 20
    volumes:
      - ./task-manager/log/:/var/log/cron/:rw
      - ./task-manager/pgbackups/:/var/opt/pgbackups/:rw

  pgadmin4:
    build:
      dockerfile: Dockerfile
      target: prod
      context: ./pgadmin4/
    secrets:
      - notes-app-pgadmin-default-password
    environment:
      PGADMIN_DEFAULT_EMAIL: kostyasolovyov54@gmail.com
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/notes-app-pgadmin-default-password
    stop_signal: SIGTERM
    stop_grace_period: 20s
    init: true
    restart: always
    depends_on:
      notes-db:
        condition: service_healthy
    networks:
      notes-nginx-reversive-proxy:
        priority: 10
      notes-notes-db:
        priority: 20
