name: Test Publish release

on:
  workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Use Node.js 18.19.1
      uses: actions/setup-node@v4
      with:
        node-version: 18.19.1
        cache: 'npm'

    - name: Instal deps
      run: npm ci

    - name: Check
      run: npx lerna run check --skip-nx-cache --since
  
    - name: Build
      run: npx run build --skip-nx-cache --since
  
    - name: Version
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx lerna version --yes
  
