name: Linting and tests

on:
  pull_request:
    branches: 
      - dev

concurrency: 
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18.19.1
      uses: actions/setup-node@v4
      with:
        node-version: 18.19.1
        cache: 'npm'
    - name: instal deps
      run: npm ci
    - name: check
      run: npm run check
