name: Publish Production

on:
  pull_request:
    branches: 
      - main
    types:
      - closed

env:
  CI: true

jobs:
  publish-release:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
    - name: Checkout 
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Use Node.js 20.13.1
      uses: actions/setup-node@v4
      with:
        node-version: 20.13.1
        cache: 'npm'

    - name: Instal root deps
      run: npm ci --workspaces=false

    - name: Instal deps
      run: |
        current_dir=$(node -e "process.stdout.write(process.cwd())")
        workspaces=$(npx lerna changed --parseable | sed "s|^$current_dir/|--workspace=|" | paste -sd ' ' -)
        npm ci $workspaces

    - name: Check
      run: npx lerna run check --skip-nx-cache --since
  
    - name: Build
      run: npx lerna run build --skip-nx-cache --since
  
    - name: Version
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"   
        json_output=$(npx lerna version --yes)
        commands=$(NODE_NO_WARNINGS=1 node --loader ts-node/esm ./tools/createLernaPushCommand.ts "$json_output")
        eval "$commands"

  update-development:
    runs-on: ubuntu-latest

    needs: [publish-release]

    permissions:
      contents: write

    steps:
    - name: Merge main to development
      run: |
        curl -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/Kallenju/notes/merges \
        -d '{"base":"development","head":"main","commit_message":"Auto-merge main to development"}'
