name: Publish release

on:
  workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest

    if: ${{ github.ref == 'refs/heads/development' }}
    
    permissions:
      contents: write

    steps:
    - name: Cancel workflow
      run: |
        curl -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/Kallenju/notes/merges \
        -d '{"base":"development","head":"main","commit_message":"Auto-merge main to development"}'

    - name: Checkout 
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Use Node.js 18.20.2
      uses: actions/setup-node@v4
      with:
        node-version: 18.20.2
        cache: 'npm'

    - name: Instal deps
      run: npm ci

    - name: Check
      run: npx lerna run check --skip-nx-cache --since
  
    - name: Build
      run: npx lerna run build --skip-nx-cache --since
  
    - name: Version
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor}}@users.noreply.github.com"   
        npx lerna version --yes
