name: Sync branches

on:
  pull_request:
    branches: 
      - main
    types:
      - closed
  
jobs:
  update-development:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Merge main to development
      run: |
        curl -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/Kallenju/notes/merges \
        -d '{"base":"development","head":"main","commit_message":"Auto-merge main to development"}'
