name: Linting and tests

on:
  pull_request:
    branches: 
      - development
      - main

concurrency: 
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
  
env:
  CI: true
  
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Use Node.js 20.13.1
      uses: actions/setup-node@v4
      with:
        node-version: 20.13.1
        cache: 'npm'

    - name: Instal deps
      run: |
        current_dir=$(node -e "process.stdout.write(process.cwd())" | sed 's|\\|/|g')
        workspaces=$(npx lerna changed --parseable | sed -E -e 's|\\|/|g' -e "s|^$current_dir/|--workspace=|" | paste -sd ' ' -)
        npm ci $workspaces

    - name: Check
      run: npx lerna run check --skip-nx-cache --since=origin/${{ github.event.pull_request.base.ref }}

    - name: Build
      run: npx lerna run build --skip-nx-cache --since=origin/${{ github.event.pull_request.base.ref }}
